---
id: byplayer-sg
tags: []
version: 0.0.1
licenses: []
author:
  markup_language: :markdown
  name: byplayer
  email: byplayer100@gmail.com
  rubygems_user: byplayer
  slideshare_user: byplayer
  speaker_deck_user: 
